### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

In [2]:
import numpy as np

1. Create a 1D array of numbers from 0 to 9

In [5]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [7]:
arr1 = np.ones((3, 3), dtype=bool)
print(arr1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


3. Create an array of numbers from 20 to 39

In [8]:
arr_num = np.arange(20, 40)
arr_num

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [13]:
# Create the 3x3 array
array_new = np.arange(20, 29).reshape((3, 3))

# Replace odd numbers with -1
array_new[array % 2 == 1] = -1

# Print the updated array
print(array_new)

[[20 -1 22]
 [-1 24 -1]
 [26 -1 28]]


5. Create two arrays of length 10 and print out  common items in both arrays

In [14]:
# Create two arrays of length 10
array1 = np.random.randint(0, 10, size=10)
array2 = np.random.randint(0, 10, size=10)

# Print the arrays
print("Array 1:", array1)
print("Array 2:", array2)

# Find the common items in both arrays
common_items = np.intersect1d(array1, array2)

# Print the common items
print("Common items:", common_items)

Array 1: [3 6 7 7 2 6 5 2 7 9]
Array 2: [5 3 6 6 7 0 2 1 9 2]
Common items: [2 3 5 6 7 9]


6.  Create a 5x5 identity matrix

In [15]:
matrix = np.identity(5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [16]:
x = np.array([10, 12, 9, 2, 20])
y = np.linspace(10, 20, 101)
z = np.ones((2, 3))

print("x =", x)
print("y =", y)
print("z =")
print(z)

x = [10 12  9  2 20]
y = [10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9 20. ]
z =
[[1. 1. 1.]
 [1. 1. 1.]]


8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [18]:
# Define array x
x = np.array([10, 12, 9, 2, 20])

# Find average and standard deviation of x
avgx = np.mean(x)
stdx = np.std(x)

print("Average of x:", avgx)
print("Standard deviation of x:",round(stdx, 2)) 

# Sort array x
x = np.sort(x)

print("Sorted x:", x)

Average of x: 10.6
Standard deviation of x: 5.78
Sorted x: [ 2  9 10 12 20]


9. Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
# Create a 10x10 array with random values between 0 and 1
arr = np.random.rand(10, 10)

# Find the minimum and maximum values in the array
min_val = np.min(arr)
max_val = np.max(arr)

print("Minimum value:", round(min_val,3))
print("Maximum value:",round(max_val,3))

Minimum value: 0.007
Maximum value: 0.988


10. Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
# Create a 3x3 matrix with values ranging from 0 to 8
matrix1 = np.arange(9).reshape(3, 3)

print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


11.  Generates an array [[1 2 3] [4 5 6]]

In [22]:
# Generate the array [[1, 2, 3], [4, 5, 6]]
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


12. Generates an array [0 2.5 5 7.5 10]

In [23]:
# Generate the array [[0,2.5,5,7.5,10]]
arr = np.array([[0,2.5,5,7.5,10]])

print(arr)

[[ 0.   2.5  5.   7.5 10. ]]


13. Generates an 3x3 array of zeros

In [24]:
arr = np.zeros((3, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


14. Create array from 0.1 to 10 with 12 elements, inclusively

In [25]:
t_t12 = np.linspace(0.1, 10, 12)

print(t_t12)

[ 0.1  1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


15. Create a matrix with seven columns and five rows of ten(10).

In [26]:
mat5 = np.ones((5, 7)) * 10

print(mat5)

[[10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10.]]


16. What is the difference between numpy and list?

NumPy arrays have built-in methods and functions for common mathematical and scientific operations, making it easier to work with arrays of data. In contrast, Python lists require you to write your own functions or use external libraries to perform the same operations.

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [27]:
arr50 = np.ones(50, dtype=int)

# Alternate the values between ones and zeros
arr50[1::2] = 0

print(arr50)

[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0]


18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [28]:
# Generate a 10x10 matrix of zeros
matz = np.zeros((10, 10))

# Make the matrix an identity matrix
np.fill_diagonal(matz, 1)

print(matz)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [29]:
# Generate a 10x10 array of zeros
arr3 = np.zeros((10, 10))

# Set diagonal components to 1
for i in range(10):
    arr3[i, i] = 1

print(arr3)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [32]:
# Define the two matrices
mat1 = np.array([[1, 2], [3, 4]])
mat2= np.array([[5, 6], [7, 8]])

# Compute the dot product
product = np.dot(mat1, mat2)

print('Product of two matrices:', product)

Product of two matrices: [[19 22]
 [43 50]]


21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [33]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A * B

print(C)

[[ 5 12]
 [21 32]]


22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [34]:
tt= np.array([[1, 2], [3, 4]])

# Perform scalar multiplication
ss = tt * 5

print(ss)

[[ 5 10]
 [15 20]]


23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [37]:
# Define the matrices A and B
A = np.array([[1, 2], [3, 4]])
 # Transpose of A
B = A.T 

# Perform matrix multiplication
C = np.dot(A, B)

print(C)

[[ 5 11]
 [11 25]]


25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [38]:
# Create the array
arr = np.array([[0, 1, 2], [3, 4, 5]])

# Extract rows and columns
A = arr[0]
B = arr[1]
C = arr[:, 1]
D = arr[0, 2]

# Print the results
print("A:", A)
print("B:", B)
print("C:", C)
print("D:", D)

A: [0 1 2]
B: [3 4 5]
C: [1 4]
D: 2
